export const ActionTypes = {
  FETCH_DOCTORS_SUCCESS: "FETCH_DOCTORS_SUCCESS",

  FETCH_CITIES: "FETCH_CITIES",
  FETCH_CITIES_SUCCESS: "FETCH_CITIES_SUCCESS",
  FETCH_CITIES_FAIL: "FETCH_CITIES_FAIL",

  // SELECTED_PRODUCT: "SELECTED_PRODUCT",
  UPDATE_DOCTOR: "UPDATE_DOCTOR",

};
